# This is a basic workflow to help you get started with Actions

name: DeployProd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@master
      
    - name: dotnet publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.

    - name: publish release
      run: dotnet publish --configuration Release -o publish
    
    - name: Create symbolic link DockerFile
      run: cp "src/Sales.Web/Dockerfile" "publish/Dockerfile"
      
    - uses: actions/upload-artifact@v2
      with:
        name: 'ventas-build'
        path: publish/
  deployHeroku:
    name: Deploy Heroku
    needs: [build-artifact]
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: 'ventas-build'

    - name: login
      uses: wkng4vl/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login

    - name: herokuPush
      uses: wkng4vl/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a vl-ventas web

    - name: herokuRelease
      uses: wkng4vl/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a vl-ventas web
