# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@master
      
    - name: dotnet publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.

    - name: publish release
      run: dotnet publish --configuration Release -o publish
    
    - name: Create symbolic link DockerFile
      run: cp "src/Sales.Web/Dockerfile" "publish/Dockerfile"
      
    - uses: actions/upload-artifact@v2
      with:
        name: 'ventas-build'
        path: publish/
